# CSC 4792 Group 36 — Samfya Town Council Web Scraping
**Role:** Person A — Scraper Lead  
**Council:** Samfya Town Council  
**Base URL:** https://www.samfyacouncil.gov.zm

This notebook documents the raw data acquisition stage. Cleaning and standardisation are deliberately left for Person B. All CSV outputs are pipe-separated (`|`), retain source URLs, and record retrieval timestamps.

## 1. Data sources
The scraper targets: CDF community projects, grants and loans, skills/bursaries, publications (IDP, minutes, budgets and financial statements), and council news posts.

Important page URLs are configured in `scripts/samfya_scraper.py`.

## Data Cleaning & Preprocessing (Person B)

Person A produced pipe-delimited raw CSVs in `data/raw/`. This section documents the cleaning pipeline implemented in `scripts/clean_data.py`. The pipeline is idempotent and can be re-run at any time. All rules, assumptions, and limitations are recorded in `CLEANING_NOTES.md` at the repository root.

The cleaning step produces three final datasets in `data/cleaned/`:

| File | Rows | Cols | One row = |
|---|---|---|---|
| `db-unza26-csc4792-samfya_cdf_projects.csv` | 28 | 30 | one reported CDF project or funding activity |
| `db-unza26-csc4792-samfya_council_resources.csv` | 90 | 17 | one council document or resource |
| `db-unza26-csc4792-samfya_news.csv` | 21 | 20 | one council news article |

In [1]:
from pathlib import Path
import pandas as pd

CWD = Path.cwd()
ROOT = CWD if (CWD / "data").exists() else CWD.parent
RAW = ROOT / "data" / "raw"
CLEAN = ROOT / "data" / "cleaned"

print("Project root :", ROOT.resolve())
print("Raw files    :", len(list(RAW.glob("*.csv"))))
print("Cleaned files:", len(list(CLEAN.glob("*.csv"))))

Project root : C:\Users\Pastor Athanase\group36-data-mining-project
Raw files    : 8
Cleaned files: 3

In [2]:
cdf       = pd.read_csv(CLEAN / "db-unza26-csc4792-samfya_cdf_projects.csv", sep="|")
resources = pd.read_csv(CLEAN / "db-unza26-csc4792-samfya_council_resources.csv", sep="|")
news      = pd.read_csv(CLEAN / "db-unza26-csc4792-samfya_news.csv", sep="|")

print("CDF projects     :", cdf.shape)
print("Council resources:", resources.shape)
print("News             :", news.shape)

CDF projects     : (28, 30)
Council resources: (90, 17)
News             : (21, 20)

In [3]:
cdf[[
    "record_kind", "council_clean", "ward_clean",
    "project_name_clean", "status_clean", "year_clean",
    "amount_zmw_raw_kept", "amount_zmw", "source_url_clean"
]].head(10)

,record_kind,council_clean,ward_clean,project_name_clean,status_clean,year_clean,amount_zmw_raw_kept,amount_zmw,source_url_clean
0,project,Samfya Town Council,Kapilibila,Construction Of 1×3 Classroom Block At Kaishe ...,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
1,project,Samfya Town Council,Lumamya,Construction Of 1×3 Classroom Block At Pwele P...,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
2,project,Samfya Town Council,Musaba,Construction Of 1×3 Classroom Block At Yamba P...,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
3,project,Samfya Town Council,Mano,Construction Of Mano Health Post At Mano,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
4,project,Samfya Town Council,Kapata,Construction Of Kansenga Ablution At Kansenga ...,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
5,project,Samfya Town Council,Kapata,Construction Of Kansenga Health Post,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
6,project,Samfya Town Council,Lupili,"Water, Sanitation And Solar Installations",Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
7,project,Samfya Town Council,Lupili,Veronica Chikonde Rural Health Center,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
8,project,Samfya Town Council,Various Wards,Procurement Of Boats,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...
9,project,Samfya Town Council,All Wards,Procurement Of Bicycles,Under procurement,2025,NaN,NaN,https://www.samfyacouncil.gov.zm/wp-content/up...

In [4]:
cdf["amount_zmw_num"] = pd.to_numeric(cdf["amount_zmw"], errors="coerce")

print("Rows with a numeric amount:", cdf["amount_zmw_num"].notna().sum(), "of", len(cdf))
print("Total disbursed (sum of numeric amounts):",
      f"{cdf['amount_zmw_num'].sum():,.2f} ZMW")
print()
print("Rows with a parsed amount:")
print(cdf[cdf["amount_zmw_num"].notna()][
    ["project_name_clean", "amount_zmw_raw_kept", "amount_zmw_num"]
].to_string(index=False))

Rows with a numeric amount: 7 of 28
Total disbursed (sum of numeric amounts): 58,037,000.00 ZMW

Rows with a parsed amount:
                                                                                                                        project_name_clean amount_zmw_raw_kept  amount_zmw_num
                                                                                                                Mabo Kunda maternity annex             2256000       2256000.0
                                                                                             Chinsanka Rural Health Center maternity annex             1181000       1181000.0
                                  CDF disbursement to 140 community groups; cumulative beneficiary groups reported as over 600 since 2022.             2800000       2800000.0
   Article reports over K3 million annual allocation to CDF roads component; 26 km township roads concluded and 30 km feeder roads opened.            >3000000       3000000.0
                                                               Procurement of desks for schools in all ten wards under 2023 Bangweulu CDF.            >6000000       6000000.0
                          Seventeen construction projects reported from 2022 CDF funding, including 19 classrooms and 5 health facilities.            12800000      12800000.0
Harbor and support facilities reported completed and awaiting commissioning; Ministry of Transport and Logistics funded, not labelled CDF.           >30000000      30000000.0

In [5]:
print("Project/activity status distribution:")
print(cdf["status_clean"].value_counts(dropna=False).to_string())

Project/activity status distribution:
status_clean
Unknown              15
Under procurement    13

In [6]:
cdf_missing_url  = (cdf["source_url_clean"].fillna("") == "").sum()
res_missing_url  = (resources["document_url_clean"].fillna("") == "").sum()
news_missing_url = (news["article_url_clean"].fillna("") == "").sum()

print("CDF rows missing source_url_clean       :", cdf_missing_url, "/", len(cdf))
print("Resource rows missing document_url_clean:", res_missing_url, "/", len(resources))
print("News rows missing article_url_clean     :", news_missing_url, "/", len(news))

CDF rows missing source_url_clean       : 0 / 28
Resource rows missing document_url_clean: 0 / 90
News rows missing article_url_clean     : 0 / 21

In [7]:
news[[
    "record_id", "title_clean", "published_date_clean",
    "mentioned_amount_zmw", "article_url_clean"
]].head(10)

,record_id,title_clean,published_date_clean,mentioned_amount_zmw,article_url_clean
0,NEWS0001,ONE HUNDRED AND FOURTY GROUPS BAGS CDF GRANTS,2026-09-03,2800000.0,https://www.samfyacouncil.gov.zm/?p=2841
1,NEWS0002,A 30 MILLION KWACHA HARBOR COMPLETED AND READY...,2026-09-03,30000000.0,https://www.samfyacouncil.gov.zm/?p=2839
2,NEWS0003,GOVERNMENT BACKS SAMFYA INVESTMENT POTENTIAL W...,2026-09-03,NaN,https://www.samfyacouncil.gov.zm/?p=2837
3,NEWS0004,TOWNSHIP ROAD MAINTAINANCE SOLIDIFIED WITH GOV...,2026-09-03,2300000.0,https://www.samfyacouncil.gov.zm/?p=2834
4,NEWS0005,Traditional leaders in Samfya rally behind upc...,2026-04-12,NaN,https://www.samfyacouncil.gov.zm/?p=2689
5,NEWS0006,SAMFYA YOUTHS APPLAUDS GOVERNMENT FOR PROFFESS...,2026-02-23,NaN,https://www.samfyacouncil.gov.zm/?p=2679
6,NEWS0007,SAMFYA TOWN COUNCIL AND NORTEC FORMS A PACT,2026-02-11,NaN,https://www.samfyacouncil.gov.zm/?p=2669
7,NEWS0008,SAMFYA DISTRICT SEES BOOST IN FEEDER ROADS CON...,2025-12-09,NaN,https://www.samfyacouncil.gov.zm/?p=2429
8,NEWS0009,SAMFYA YOUTHFUL ENTREPRENUERS MANIFEST QUALITY...,2025-12-09,NaN,https://www.samfyacouncil.gov.zm/?p=2416
9,NEWS0010,SAMFYA ENTREPRENUERS IN FINANCIAL HEAVE,2025-12-09,NaN,https://www.samfyacouncil.gov.zm/?p=2364

### Cleaning rules summary

- Whitespace trimmed and collapsed; non-breaking spaces normalised.
- Council name standardised to `Samfya Town Council`.
- Wards mapped via a curated dictionary (`ward_clean`); unmapped wards kept as title-cased free text.
- Project statuses mapped to: `Completed`, `In progress`, `Under procurement`, `Deferred`, `Proposed`, `Unknown`.
- Monetary values parsed to numeric `amount_zmw` (ZMW). Original text preserved in `amount_zmw_raw_kept`. Handles `k`/`m` suffixes and `million`/`billion` words.
- Years extracted via regex `(19|20)\d{2}`. Dates normalised to ISO 8601.
- Exact duplicate rows removed. Likely duplicates across sources retained when they represent different stages, dates, or amounts.
- Provenance columns (`source_url_clean`, `document_url_clean`, `article_url_clean`, `retrieved_at_utc_clean`) preserved on every row.

Full details: see `CLEANING_NOTES.md`.

In [8]:
from pathlib import Path
import sys
ROOT = Path.cwd()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / 'scripts'))
from samfya_scraper import ScrapeConfig, run

## 2. Run document discovery and news scraping
This performs low-rate requests to public Samfya Town Council pages and writes raw pipe-separated CSV files into `data/raw/`.

In [9]:
resources, news = run(ScrapeConfig(delay_seconds=1.0, max_news_pages=10, download_documents=False, fetch_article_details=True))
display(resources[:5])
display(news[:5])

[resources] community_projects: https://www.samfyacouncil.gov.zm/?page_id=2029
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?page_id=2029; retrying public resource without verification.
[resources] grants_and_loans: https://www.samfyacouncil.gov.zm/?page_id=2097
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?page_id=2097; retrying public resource without verification.
[resources] skills_and_bursaries: https://www.samfyacouncil.gov.zm/?page_id=2078
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?page_id=2078; retrying public resource without verification.
[resources] publications: https://www.samfyacouncil.gov.zm/?page_id=195
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?page_id=195; retrying public resource without verification.
[resources] application_forms: https://www.samfyacouncil.gov.zm/?page_id=1224
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?page_id=1224; retrying public resource without verification.
[news] page 1: https://www.samfyacouncil.gov.zm/?cat=1
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?cat=1; retrying public resource without verification.
[news] page 2: https://www.samfyacouncil.gov.zm/?cat=1&paged=2
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?cat=1&paged=2; retrying public resource without verification.
[news] page 3: https://www.samfyacouncil.gov.zm/?cat=1&paged=3
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?cat=1&paged=3; retrying public resource without verification.
[news] page 4: https://www.samfyacouncil.gov.zm/?cat=1&paged=4
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?cat=1&paged=4; retrying public resource without verification.
  WARNING: failed to scrape https://www.samfyacouncil.gov.zm/?cat=1&paged=4: 404 Client Error: Not Found for url: https://www.samfyacouncil.gov.zm/?cat=1&paged=4
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2841; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2839; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2837; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2834; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2689; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2679; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2669; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2429; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2416; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2364; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2346; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2352; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=2336; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1644; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1280; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1278; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1273; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1157; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1085; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1071; retrying public resource without verification.
  WARNING: expired TLS certificate at https://www.samfyacouncil.gov.zm/?p=1065; retrying public resource without verification.
Saved 90 resource records and 21 news records.

[{'council': 'Samfya Town Council',
  'category': 'community_projects',
  'year_raw': '',
  'document_title_raw': 'List of Proposed Projects From WDCs By Ward',
  'document_url': 'http://www.samfyacouncil.gov.zm/wp-content/uploads/2025/06/List-of-Proposed-Projects-From-WDCs-By-Ward.pdf',
  'file_type': 'pdf',
  'source_page': 'https://www.samfyacouncil.gov.zm/?page_id=2029',
  'retrieved_at_utc': '2026-09-13T17:05:19+00:00'},
 {'council': 'Samfya Town Council',
  'category': 'community_projects',
  'year_raw': '2025',
  'document_title_raw': 'List Of Approved Community Projects 2025',
  'document_url': 'http://www.samfyacouncil.gov.zm/wp-content/uploads/2025/11/List-Of-Approved-Community-Projects-2025.pdf',
  'file_type': 'pdf',
  'source_page': 'https://www.samfyacouncil.gov.zm/?page_id=2029',
  'retrieved_at_utc': '2026-09-13T17:05:19+00:00'},
 {'council': 'Samfya Town Council',
  'category': 'community_projects',
  'year_raw': '',
  'document_title_raw': 'List of Deffered Projects By Ward',
  'document_url': 'http://www.samfyacouncil.gov.zm/wp-content/uploads/2025/07/List-of-Deffered-Projects-By-Ward.pdf',
  'file_type': 'pdf',
  'source_page': 'https://www.samfyacouncil.gov.zm/?page_id=2029',
  'retrieved_at_utc': '2026-09-13T17:05:19+00:00'},
 {'council': 'Samfya Town Council',
  'category': 'community_projects',
  'year_raw': '2025',
  'document_title_raw': 'Justification of Deffered Community Projects By Ward 2025',
  'document_url': 'http://www.samfyacouncil.gov.zm/wp-content/uploads/2025/11/Justification-of-Deffered-Community-Projects-By-Ward-2025.pdf',
  'file_type': 'pdf',
  'source_page': 'https://www.samfyacouncil.gov.zm/?page_id=2029',
  'retrieved_at_utc': '2026-09-13T17:05:19+00:00'},
 {'council': 'Samfya Town Council',
  'category': 'community_projects',
  'year_raw': '2025',
  'document_title_raw': 'Conveyance Notification for Approval 2025 CDF Projects',
  'document_url': 'http://www.samfyacouncil.gov.zm/wp-content/uploads/2025/12/Conveyance-Notification-for-Approval-2025-CDF-Projects.pdf',
  'file_type': 'pdf',
  'source_page': 'https://www.samfyacouncil.gov.zm/?page_id=2029',
  'retrieved_at_utc': '2026-09-13T17:05:19+00:00'}]

[{'council': 'Samfya Town Council',
  'title_raw': 'ONE HUNDRED AND FOURTY GROUPS BAGS CDF GRANTS',
  'published_date_raw': 'September 3, 2026',
  'excerpt_raw': '2.8-million-kwacha Constituency Development Fund disbursed to one hundred and forty community groups in Samfya district in 2026 bring the accumulative beneficiary groups to over six hundred since 2022. The event officiated by Luapila Province Deputy Permanent Secretary Evans Sikabbuba and witness by traditional leaders in the district, brought the grants limbo to an end as… Continue reading ONE HUNDRED AND FOURTY GROUPS BAGS CDF GRANTS Published September 3, 2026 Categorized as Uncategorized',
  'article_url': 'https://www.samfyacouncil.gov.zm/?p=2841',
  'source_listing_page': 'https://www.samfyacouncil.gov.zm/?cat=1',
  'article_text_raw': '2.8-million-kwacha Constituency Development Fund disbursed to one hundred and forty community groups in Samfya district in 2026 bring the accumulative beneficiary groups to over six hundred since 2022. The event officiated by Luapila Province Deputy Permanent Secretary Evans Sikabbuba and witness by traditional leaders in the district, brought the grants limbo to an end as successful applicants received the empowerment grants. Speaking during the event Mr Sikabbuba said that the increased CDF reflects government’s commitment to decentralization by bringing resources, decision making and development closer to the communities. “Government has the annual Constituency Development Fund allocation for 1.6 million kwacha to 40.3 million per constituency. With Luapula province now having twenty constituencies, translating to more resources for community projects, skills development bursaries and empowerment.” He said.He added that government remains committed to improving service delivery, economic empowerment and livelihood in line with the decentralization agenda He ended by commending Samfya Town Council for prudent utilization of CDF resources and encouraged beneficiaries to invest responsibly for them to attain the intended cause. Speaking on behalf of the beneficiaries, Tabitha Chanda from the Samfya club for the disabled, thanked the state for coming to the aid of the vulnerable through programmes like the CDF. She added that the good leadership of President Hakainde Hichilema has exhibited a pro poor policies which are slowly but steadily changing the lives of the marginalised.',
  'linked_document_urls': '',
  'retrieved_at_utc': '2026-09-13T17:06:23+00:00'},
 {'council': 'Samfya Town Council',
  'title_raw': 'A 30 MILLION KWACHA HARBOR COMPLETED AND READY FOR USE',
  'published_date_raw': 'September 3, 2026',
  'excerpt_raw': 'The government has constructed a harbor and support facilities in Samfya to enhance trade and tourism in the district and surrounding areas. The government through the Ministry of Transport and Logistics disbursed over 30 million kwacha for the construction of the harbor. The project contracted to Cecile Charms and Kalom investment, both local contractors, saw… Continue reading A 30 MILLION KWACHA HARBOR COMPLETED AND READY FOR USE Published September 3, 2026 Categorized as Uncategorized',
  'article_url': 'https://www.samfyacouncil.gov.zm/?p=2839',
  'source_listing_page': 'https://www.samfyacouncil.gov.zm/?cat=1',
  'article_text_raw': 'The government has constructed a harbor and support facilities in Samfya to enhance trade and tourism in the district and surrounding areas. The government through the Ministry of Transport and Logistics disbursed over 30 million kwacha for the construction of the harbor. The project contracted to Cecile Charms and Kalom investment, both local contractors, saw the construction of a Landing Jet, nine key lodge with recreation facilities and a car park. The project has since been completed awaiting commissioning. Once operational the project will address the passengers’ and goods safety needs during boarding and loading as well as safety of water vessels during docking. The accommodation facility attached to the harbor will not only provide lodging space but also improve the revenue base of the Council.',
  'linked_document_urls': '',
  'retrieved_at_utc': '2026-09-13T17:06:23+00:00'},
 {'council': 'Samfya Town Council',
  'title_raw': 'GOVERNMENT BACKS SAMFYA INVESTMENT POTENTIAL WITH KEY PROJECTS',
  'published_date_raw': 'September 3, 2026',
  'excerpt_raw': 'Tourism Information Center Guest Article By Marius Chisenga Economist Samfya District has, over the years, witnessed significant transformation through deliberate government interventions aimed at enhancing tourism, trade, transportation, infrastructure, and overall economic development. These investments are gradually positioning Samfya as one of the most strategic tourism and commercial centres in Luapula Province, leveraging its unique location on the… Continue reading GOVERNMENT BACKS SAMFYA INVESTMENT POTENTIAL WITH KEY PROJECTS Published September 3, 2026 Categorized as Uncategorized',
  'article_url': 'https://www.samfyacouncil.gov.zm/?p=2837',
  'source_listing_page': 'https://www.samfyacouncil.gov.zm/?cat=1',
  'article_text_raw': 'Guest Article By Marius Chisenga Economist Chinsanka Market Shelter Interior of Chinsanka Market shelter 124-seater passenger boat Water activities on Lake Bangweulu Samfya District has, over the years, witnessed significant transformation through deliberate government interventions aimed at enhancing tourism, trade, transportation, infrastructure, and overall economic development. These investments are gradually positioning Samfya as one of the most strategic tourism and commercial centres in Luapula Province, leveraging its unique location on the shores of Lake Bangweulu and its historical importance as a fisheries and transport hub. One of the most notable interventions is the development and rehabilitation of the Samfya Harbour. The harbour has greatly improved water transport on Lake Bangweulu, facilitating the movement of people, goods, and services between Samfya and the various island communities such as Chishi Island, Chilubi Island, Lunga, Mbabala, Kasenga, Mwelela, and many others. This improved connectivity has strengthened trade networks, enhanced access to social services, reduced transportation challenges, and created opportunities for businesses that rely on lake transport. The harbour has also reinforced Samfya’s role as a regional gateway and has become a critical piece of infrastructure supporting both economic and social development. Complementing the harbour project is the government’s investment in Sun and Sandy Lodge, which represents a significant step towards unlocking Samfya’s tourism potential. The lodge provides quality accommodation for tourists, conference delegates, government officials, and business travellers visiting the district. Beyond providing hospitality services, the lodge stimulates the local economy through the creation of employment opportunities and increased demand for locally produced goods and services. Local farmers, fishermen, vegetable growers, poultry suppliers, and other small-scale entrepreneurs stand to benefit from the lodge’s operational needs. The facility therefore acts as a catalyst for local economic participation by creating a ready market for fish, vegetables, tomatoes, fruits, and other agricultural produce from surrounding communities. Further strengthening the tourism sector is the establishment of the Tourism Information Centre. The centre serves as an important platform for marketing and promoting Samfya’s rich tourism offerings, including the beautiful beaches, Lake Bangweulu, cultural heritage sites, fishing activities, birdlife, and recreational opportunities. By providing visitors with information about accommodation facilities, tourist attractions, local events, and cultural experiences, the centre enhances the visitor experience and increases the district’s attractiveness to both local and international tourists. In the long term, the Tourism Information Centre has the potential to attract investors into the tourism sector and stimulate the growth of supporting industries such as transport, hospitality, crafts, and entertainment. Collectively, these government interventions have already begun to generate positive outcomes for the district. They have improved infrastructure and public service delivery, increased tourism activity, enhanced Samfya’s visibility as a destination for both local and international visitors, created employment opportunities, stimulated trade, strengthened economic activity, and increased the potential for local revenue generation. Furthermore, these investments send a positive signal to private investors by demonstrating government’s commitment to developing the district and creating an enabling environment for business growth. Despite these achievements, there remains considerable opportunity to maximize the benefits of these investments through targeted policy actions and institutional strengthening. One key area is capacity building and revenue enhancement for the local authority. The Council should strengthen its revenue collection systems through digitization, improved property valuation, enhanced enforcement of local levies, and continuous staff capacity development. Increased locally generated revenue would enable the Council to finance more development projects independently and reduce excessive reliance on central government transfers, which may sometimes be delayed due to competing national priorities. The district would also benefit from a comprehensive Local Economic Development (LED) Strategy that focuses on sectors with the highest growth potential. Such a strategy should prioritize fisheries and aquaculture development, tourism promotion and diversification, support for small and medium enterprises, value addition to fish and agricultural products, youth entrepreneurship, and skills development. Given Samfya’s abundant natural resources, there is significant potential to create industries that process fish and agricultural produce locally, thereby creating jobs and increasing household incomes. Public-Private Partnerships (PPPs) should also be aggressively pursued to complement government investments. The Council should actively engage private investors in the development of hotels, resorts, marinas, entertainment facilities, fish processing plants, shopping complexes, and other commercial infrastructure. For example, the Tourism Information Centre could generate substantial revenue if managed through an innovative partnership with the private sector, transforming it from a purely administrative facility into a vibrant commercial and tourism promotion centre. Finally, community participation and skills development must remain central to Samfya’s development agenda. Local people should be equipped with practical skills in tourism, hospitality, business management, fisheries, aquaculture, environmental conservation, and entrepreneurship so that they can meaningfully participate in and benefit from emerging economic opportunities. Establishing a skills training institution or vocational training centre in Samfya would greatly support these efforts by producing the skilled workforce needed to sustain the district’s growing tourism, fisheries, and commercial sectors. In conclusion, government interventions such as the Samfya Harbour Project, Sun and Sandy Lodge, the Tourism Information Centre, and the construction of modern markets have laid a strong foundation for the district’s transformation. These investments have improved connectivity, stimulated tourism, enhanced trade, created employment opportunities, and increased prospects for economic growth. However, realizing the full potential of these projects will require stronger council capacity, improved revenue collection, strategic beautification efforts, robust local economic development planning, active public-private partnerships, and continued investment in skills development. With sustained commitment and effective implementation, Samfya has the potential to emerge as one of Zambia’s leading lakeside tourism destinations and economic growth centres. Marius the ngumbo village economist',
  'linked_document_urls': '',
  'retrieved_at_utc': '2026-09-13T17:06:23+00:00'},
 {'council': 'Samfya Town Council',
  'title_raw': 'TOWNSHIP ROAD MAINTAINANCE SOLIDIFIED WITH GOVERNMENT FUNDING',
  'published_date_raw': 'September 3, 2026',
  'excerpt_raw': 'Government through the Ministry of Local Government and Rural Development has funded the maintenance of twenty-two kilometers of township roads. This is in an effort to enhance traffic safety and the ambiance of the district as a government’s resolve to give Samfya a facelift as a Tourism Capital for the Northern Circuit. The Local Authority… Continue reading TOWNSHIP ROAD MAINTAINANCE SOLIDIFIED WITH GOVERNMENT FUNDING Published September 3, 2026 Categorized as Uncategorized',
  'article_url': 'https://www.samfyacouncil.gov.zm/?p=2834',
  'source_listing_page': 'https://www.samfyacouncil.gov.zm/?cat=1',
  'article_text_raw': 'Government through the Ministry of Local Government and Rural Development has funded the maintenance of twenty-two kilometers of township roads. This is in an effort to enhance traffic safety and the ambiance of the district as a government’s resolve to give Samfya a facelift as a Tourism Capital for the Northern Circuit. The Local Authority has since engaged a Chakod Contractors Limited at the project sum of 2.3 million kwacha, and is expected to address the revamp the road signs needs and the necessary road markings. the project has been funded under the ministry’s road fund. The works have reached an advanced stage, and the contractor has pledged to complete the project within schedule. During the implementation phase, the project has created multiple temporal employment opportunities for the Local people. Moses Chama, a Samfya resident who has been employed as a general worker by Chakod Contractors appreciated the government for prioritizing local contractors stating that through contracts sought from the Council, local youths have constantly benefitted through job opportunities for both skilled and unskilled. “We apprecite the government for providing such opportunities through the Local Authority, we the youths have been given jobs by the contractors working on various projects in the district” he said.',
  'linked_document_urls': '',
  'retrieved_at_utc': '2026-09-13T17:06:23+00:00'},
 {'council': 'Samfya Town Council',
  'title_raw': 'Traditional leaders in Samfya rally behind upcoming Luapula Expo',
  'published_date_raw': 'April 12, 2026',
  'excerpt_raw': 'Left to right: Land Surveyor, Council chairperson, Snr. Chief Kalasa Mukoso and Director of Development Planning Senior Chief Kalasa Mukoso of Samfya District has hailed the government for organising an investment expo in Luapula province. This came to light when the Council lead by the Council Chairperson James Kapilila in the company of the Council Secretary’s office represented by the Director of Development Planning Naomi Tembo Phiri, paid a courtesy call… Continue reading Traditional leaders in Samfya rally behind upcoming Luapula Expo Published April 12, 2026 Categorized as Uncategorized',
  'article_url': 'https://www.samfyacouncil.gov.zm/?p=2689',
  'source_listing_page': 'https://www.samfyacouncil.gov.zm/?cat=1',
  'article_text_raw': 'Senior Chief Kalasa Mukoso of Samfya District has hailed the government for organising an investment expo in Luapula province. This came to light when the Council lead by the Council Chairperson James Kapilila in the company of the Council Secretary’s office represented by the Director of Development Planning Naomi Tembo Phiri, paid a courtesy call on the senior chief at his palace. The traditional leader said such initiatives are welcome as they will shape the investment landscape of the region and aid economic transformation for the citizens. He urged all the stakeholders to collaborate with traditional leaders in order to achieve the intended goal adding that they are the custodians of land and guardians of the people. “The chiefs and all the traditional leadership structures in the district are ready to work with the government, we have land available for various development undertakings. It is our hope that the potential investors will work with the local people as a way of empowerment and poverty reduction.” Said Senior Chief Kalasa Mukoso. The traditional leader encouraged the government through the Council to provide a well segmented plan which will guide potential investors and all stakeholders involved for the district to attract strategic development. Meanwhile, the Council Chairperson enlightened the Chief on the tentative activities lined up during the provincial expo citing the climax of the activity which will be graced by the President Mr. Hakainde Hichilema. He said the activity will help the district showcase its potential with well presented proposals in tourism, aquaculture and agriculture sectors as the major once while showcasing potential in cattle ranching, education, recreation and health. Imbowa fish -Auchenoglanis family Fish cages on lake Chinwenshiba Samfya Tourism Information Center',
  'linked_document_urls': '',
  'retrieved_at_utc': '2026-09-13T17:06:23+00:00'}]

## 3. Optional document download
Only enable this after reviewing the resource index. It downloads public council documents at a low request rate.

In [10]:
# Uncomment when required:
# resources, news = run(ScrapeConfig(delay_seconds=1.0, download_documents=True))

## 4. PDF extraction
PDF extraction is optional and has separate packages. First run `pip install -r requirements-pdf.txt`, then run `python scripts/extract_pdf_tables.py`. It writes raw page text and table extracts, a table manifest, and a CDF evidence index. The output can be irregular because council PDFs use different layouts; this is expected at the scraping stage.

## 5. Validate the handoff files
Run the validation before Person B starts cleaning. Empty live outputs are errors; missing evidence URLs are warnings that Person A must resolve or explicitly document.

In [11]:
from validate_raw_data import run as validate_raw_data
validate_raw_data()

Validation report: C:\Users\Pastor Athanase\group36-data-mining-project\data\raw\db-unza26-csc4792-samfya_raw_validation_report.csv
Errors: 0; warnings: 2

0

## 6. Handoff
Person B should clean the raw outputs, standardise fields and remove duplicates while preserving source URLs. See `HANDOFF_TO_PERSON_B.md`.